### ISSUE TITLE
The test for blogs__vue-vuex-rest do not pass

### ISSUE THREAD

**Issue by alukos** [cypress-io/cypress-example-recipes#137]
MacOS
Cypress v2.1.0

CLI, GNU all tests pass except for blogs__vue-vuex-rest
![2018-04-10 12 38 42](https://user-images.githubusercontent.com/1665776/38549299-60df6068-3cbc-11e8-9e0c-7487f02b45e0.png)

```
npm i # ok
npm start
> cypress-example-recipes@0.0.0 start /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes
> node ./scripts/start.js

Running 'npm start' in cypress-example-codepen
Running 'npm start' in cypress-example-angular

Running 'npm start' in cypress-example-api-testing

Running 'npm start' in cypress-example-e2e-snapshots
Running 'npm start' in cypress-example-vue-vuex-rest
Running 'npm start' in logging-in-csrf-tokens
Running 'npm start' in logging-in-html-web-form
Running 'npm start' in logging-in-single-sign-on
Running 'npm start' in logging-in-xhr-web-form
Running 'npm start' in cypress-example-typescript-browserify
Running 'npm start' in cypress-example-typescript-webpack

Running 'npm start' in bootstrapping-your-app

Running 'npm start' in stubbing-google-analytics

Running 'npm start' in stubbing-window
Running 'npm start' in spy-stub-clock

Running 'npm start' in drag-n-drop
Running 'npm start' in form-interactions
Running 'npm start' in tab-handling-anchor-links
Running 'npm start' in hover-hidden-elements

Done booting all servers. Ready to run Cypress.


  \{^_^}/ hi!
  \{^_^}/ hi!


  Loading data.json
  Loading data.json
  Loading ../../node_modules/json-server-reset
  Loading ../../node_modules/json-server-reset
  Done
  Done

  Resources
  http://localhost:3700/todos

  Home
  http://localhost:3700

  Type s + enter at any time to create a snapshot of the database

  Resources
  http://localhost:3000/todos

  Home
  http://localhost:3000

  Type s + enter at any time to create a snapshot of the database
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at doListen (net.js:1522:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
GET /todos 200 7.556 ms - 81
resetting database
POST /reset 200 18.415 ms - -
POST /todos 201 2.934 ms - 62
```
```
npm run cypress:run 
# ok except for blogs__vue-vuex-rest
cd ./example/blogs__vue-vuex-rest
npm run cypress:run 
> cypress-example-vue-vuex-rest@1.0.0 cypress:run /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest
> ../../node_modules/.bin/cypress run

  (Tests Starting)


  1) initial todos
  2) loads the app
  via API
    3) "before each" hook: resetDatabase for "adds todo"

  API
    4) "before each" hook: resetDatabase for "receives empty list of items"

  UI to Vuex store
    5) "before each" hook: resetDatabase for "has loading, newTodo and todos properties"

  Vuex store
    6) "before each" hook: resetDatabase for "starts empty"

  Store actions
    7) "before each" hook: resetDatabase for "changes the state"

  UI
    8) "before each" hook: resetDatabase for "uploads file with todos"


  0 passing (3s)
  8 failing

  1)  initial todos:
     CypressError: cy.visit() failed trying to load:

http://localhost:3000/

The content-type of the response we received from your web server was:

  > application/openapi+json

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

cy.request() will automatically get and set cookies and enable you to parse responses.
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:66781:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:66746:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:66773:17)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58318:31
      at visitFailedByErr (http://localhost:3000/__cypress/runner/cypress_runner.js:57936:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58299:22
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:6846:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:4868:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:4925:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:4970:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:5045:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:1778:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:1788:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:1662:14)
      at <anonymous>
...

  (Tests Finished)

  - Tests:           2
  - Passes:          0
  - Failures:        8
  - Pending:         0
  - Duration:        3 seconds
  - Screenshots:     8
  - Video Recorded:  false
  - Cypress Version: 2.1.0


  (Screenshots)

  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/initial todos.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/loads the app.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/viaAPI -- adds todo -- before each hook resetDatabase.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/API-- receives empty list of items -- before each hook resetDatabase.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/UI to Vuex store -- has loading newTodo and todos properties -- before each hook resetDatabase.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/Vuex store -- starts empty -- before each hook resetDatabase.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/Store actions -- changes the state -- before each hook resetDatabase.png (2560x1440)
  - /Users/alukos/proj/src/sandbox/Cypress/cypress-example-recipes/examples/blogs__vue-vuex-rest/cypress/screenshots/UI -- uploads file with todos -- before each hook resetDatabase.png (2560x1440)


  (All Done)

npm ERR! code ELIFECYCLE
npm ERR! errno 8
npm ERR! cypress-example-vue-vuex-rest@1.0.0 cypress:run: `../../node_modules/.bin/cypress run`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the cypress-example-vue-vuex-rest@1.0.0 cypress:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alukos/.npm/_logs/2018-04-10T09_17_15_984Z-debug.log
```

**Comment by jennifer-shehane** [comment]
One of the tests run is on port 3000, which seems to be in use already on your machine. Make sure to kill any running process on port 3000 first. 

```
Error: listen EADDRINUSE 0.0.0.0:3000
```

**Comment by bahmutov** [comment]
Yes, seems you have already a server running at that port 3000!
