### ISSUE TITLE
AppVeyor Windows build is failing

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#388]
Just timing out on the very first recipe, waiting for the url to respond. Example https://ci.appveyor.com/project/cypress-io/cypress-example-recipes/builds/29701131

```
npm run test:ci:windows
-------------------------------------------
Testing examples/blogs__application-actions
-------------------------------------------
> blogs__page-actions@1.0.0 test:ci:windows C:\projects\cypress-example-recipes\examples\blogs__application-actions
> bin-up start-test start:win 8888 cypress:run:win
starting server using command "npm run start:win"
and when url "http://localhost:8888" is responding
running tests using command "npm run cypress:run:win"
> blogs__page-actions@1.0.0 start:win C:\projects\cypress-example-recipes\examples\blogs__application-actions
> bin-up http-server -p 8888 --silent -c-1
Error: Timeout
    at Timeout._onTimeout (C:\projects\cypress-example-recipes\node_modules\start-server-and-test\node_modules\wait-on\lib\wait-on.js:113:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Problem running command "start-test" 
found at C:\projects\cypress-example-recipes\node_modules\.bin\start-test
C:\projects\cypress-example-recipes\node_modules\.bin\start-test start:win 8888 cypress:run:win
undefined
```

Note: the AppVeyor cache also has multiple versions of Test Runner binary

```
ls '%USERPROFILE%\AppData\Local\Cypress\Cache' || true
3.4.1
3.5.0
3.6.0
3.6.1
3.7.0
3.8.0
npm ci

```

Related: add Cypress prune command https://github.com/cypress-io/cypress/issues/5972

**Comment by bahmutov** [comment]
Could it be a bug in `bin-up` https://github.com/bahmutov/bin-up ?

**Comment by bahmutov** [comment]
```
> blogs__page-actions@1.0.0 start:win C:\projects\cypress-example-recipes\examples\blogs__application-actions
> bin-up http-server -p 8888 --silent -c-1
Found C:\projects\cypress-example-recipes\node_modules\.bin\http-server
```
It does find the right tool, let's try using older version of `bin-up`

**Comment by bahmutov** [comment]
hmm, `bin-up` is finding the right tools the server is not responding 

```
> bin-up http-server -p 8888 -c-1
Found C:\projects\cypress-example-recipes\node_modules\.bin\http-server
found tool "http-server" at "C:\projects\cypress-example-recipes\node_modules\.bin\http-server"
running C:\projects\cypress-example-recipes\node_modules\.bin\http-server [ '-p', '8888', '-c-1' ]
Starting up http-server, serving ./
Available on:
  http://10.0.0.12:8888
  http://127.0.0.1:8888
Hit CTRL-C to stop the server
[2019-12-23T15:43:07.417Z] "HEAD /" "undefined"
(node:2904) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2019-12-23T15:43:09.405Z] "HEAD /" "undefined"
[2019-12-23T15:43:11.408Z] "HEAD /" "undefined"
[2019-12-23T15:43:13.410Z] "HEAD /" "undefined"
[2019-12-23T15:43:15.399Z] "HEAD /" "undefined"
[2019-12-23T15:43:17.411Z] "HEAD /" "undefined"
[2019-12-23T15:43:19.403Z] "HEAD /" "undefined"
[2019-12-23T15:43:21.406Z] "HEAD /" "undefined"
[2019-12-23T15:43:23.414Z] "HEAD /" "undefined"
```

**Comment by bahmutov** [comment]
Locally on Mac, it is working - even with `HTTP`

**Comment by brian-mann** [comment]
Looks like `http-server` is mounting on `127.0.0.1` and `10.0.0.12`. However I wonder if `wait-on` is requesting `localhost` or another different IP address. If localhost isnt mapped to `127.0.0.1` that would cause it.

Also `wait-on` is issuing a `HEAD` request. What is that `"undefined"` output in the logs? Does `http-server` actually listen to anything via a `HEAD` request?

I think `http-server` is fine, the problem is `wait-on`.

**Comment by bahmutov** [comment]
yeah, `wait-on` sometimes gets confused and never finishes. I have added debug env variable to see the output from `wait-on` in this case

**Comment by bahmutov** [comment]
ughh, yes, it is `wait-on` mistake
```

Found C:\projects\cypress-example-recipes\node_modules\.bin\http-server
found tool "http-server" at "C:\projects\cypress-example-recipes\node_modules\.bin\http-server"
running C:\projects\cypress-example-recipes\node_modules\.bin\http-server [ '-p', '8888', '-c-1' ]
Starting up http-server, serving ./
Available on:
  http://10.0.0.25:8888
  http://127.0.0.1:8888
Hit CTRL-C to stop the server
[2019-12-23T16:12:48.106Z] "GET /" "undefined"
(node:2840) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
child next [ { 'http-get://localhost:8888': -999 } ]
wait-on(3016) waiting for: http-get://localhost:8888
child complete
[2019-12-23T16:12:49.096Z] "GET /" "undefined"
[2019-12-23T16:12:51.073Z] "GET /" "undefined"
child next []
child complete
[2019-12-23T16:12:53.086Z] "GET /" "undefined"
child next []
child complete
[2019-12-23T16:12:55.073Z] "GET /" "undefined"
child next []
child complete
```
Which is something known https://github.com/jeffbski/wait-on/issues/30 ughh

**Comment by bahmutov** [comment]
ughh, trying to wait-on `http://127.0.0.1:8888` fails the same way
```

Found C:\projects\cypress-example-recipes\node_modules\.bin\http-server
found tool "http-server" at "C:\projects\cypress-example-recipes\node_modules\.bin\http-server"
running C:\projects\cypress-example-recipes\node_modules\.bin\http-server [ '-p', '8888', '-c-1' ]
Starting up http-server, serving ./
Available on:
  http://10.0.0.15:8888
  http://127.0.0.1:8888
Hit CTRL-C to stop the server
[2019-12-23T19:07:01.724Z] "HEAD /" "undefined"
(node:2012) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
child next [ { 'http://127.0.0.1:8888': -999 } ]
wait-on(1368) waiting for: http://127.0.0.1:8888
child complete
[2019-12-23T19:07:02.703Z] "HEAD /" "undefined"
[2019-12-23T19:07:04.700Z] "HEAD /" "undefined"
child next []
child complete
[2019-12-23T19:07:06.698Z] "HEAD /" "undefined"
child next []
child complete
[2019-12-23T19:07:08.696Z] "HEAD /" "undefined"
child next []
child complete
[2019-12-23T19:07:10.703Z] "HEAD /" "undefined"
child next []
```

and trying to use `got` via ping gives an invalid url, but only on Windows?!

```
starting server using command "npm run start:win"
and when url "[ 'ping-http://localhost:8888' ]" is responding
running tests using command "npm run cypress:run:win"
2019-12-23T16:40:10.442Z start-server-and-test starting server with command "npm run start:win", verbose mode? true
2019-12-23T16:40:10.457Z start-server-and-test using own ping ping-http://localhost:8888
2019-12-23T16:40:10.457Z start-server-and-test pinging url "http://localhost:8888"
> blogs__page-actions@1.0.0 start:win C:\projects\cypress-example-recipes\examples\blogs__application-actions
> bin-up http-server -p 8888 -c-1
Found C:\projects\cypress-example-recipes\node_modules\.bin\http-server
found tool "http-server" at "C:\projects\cypress-example-recipes\node_modules\.bin\http-server"
running C:\projects\cypress-example-recipes\node_modules\.bin\http-server [ '-p', '8888', '-c-1' ]
Starting up http-server, serving ./
Available on:
  http://10.0.0.36:8888
  http://127.0.0.1:8888
Hit CTRL-C to stop the server
[2019-12-23T16:40:11.489Z] "GET /" "got/9.6.0 (https://github.com/sindresorhus/got)"
(node:2988) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(node:2812) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at ClientRequest.handleResponse (C:\projects\cypress-example-recipes\node_modules\start-server-and-test\node_modules\got\source\request-as-event-emitter.js:133:27)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (C:\projects\cypress-example-recipes\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at Socket.socketOnData (_http_client.js:456:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
(node:2812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by brian-mann** [comment]
It looks like you didn't supply a valid URL. It looks like you only supplied `/` perhaps?

**Comment by bahmutov** [comment]
Not, the server literally logged the response!

```
[2019-12-23T16:40:11.489Z] "GET /" "got/9.6.0 (https://github.com/sindresorhus/got)"
```

So it is a bug inside the `got` that might be https://github.com/sindresorhus/got/issues/604 which should have been handled by `got` - and also I don't see redirect returned from `http-server` ...
