### ISSUE TITLE
Error Cannot find module 'babel-register' on CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#393]
Example CI runs:
- https://circleci.com/gh/cypress-io/cypress-test-example-repos/72051#tests/containers/9

```
> seeding-your-database@1.0.0 test:ci /root/app/examples/server-communication__seeding-database-in-node
> ../../node_modules/.bin/start-test 7082 cypress:run

starting server using command "npm run start"
and when url "http://localhost:7082" is responding
running tests using command "npm run cypress:run"

> seeding-your-database@1.0.0 start /root/app/examples/server-communication__seeding-database-in-node
> node server/index.js --port 7082

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/app/examples/server-communication__seeding-database-in-node/server/index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by bahmutov** [comment]
turns out we missed the example `server-communication__seeding-database-in-node` when running jobs on CI, so it was only running when scripts testing all examples were running. Fixed, plus added missing dependency.
