### ISSUE TITLE
Add example for stubbing `navigator.cookieEnabled`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-recipes#483]
From https://github.com/cypress-io/cypress/issues/7015#issuecomment-614538787, should be linked from these examples https://github.com/cypress-io/cypress-example-recipes#stubbing-and-spying

`index.html`

```html
<html>
<body>
    <div id="message"><div>
</body>
<script>
    if (navigator.cookieEnabled === false) {
       document.getElementById("message").innerHTML = "Error: cookies not enabled!"
    } else {
       document.getElementById("message").innerHTML = "Yay! cookies are enabled!"
    }
</script>
</html>
```

`spec.js`

```js
it('cookies are disabled for user', () => {
  cy.visit('index.html', {
    onBeforeLoad(win) {
      cy.stub(win.navigator, 'cookieEnabled', false).as('cookieEnabled')
    },
  })

  cy.get('#message').should('contain', 'Error: cookies not enabled!')
})

it('cookies are enabled for user', () => {
  cy.visit('index.html')

  cy.get('#message').should('contain', 'Yay! cookies are enabled!')
})
```

**Comment by ArneCaluwe** [comment]
I would like to give this a go

**Comment by JohnnyDevNull** [comment]
The mentioned solution doesn't work for multiple redirects, e.g. you want to visit `/` the root of your application. Then some guard redirecting you to a cookies page. Between the redirects Cypress does not keep the stub.

So i've figured out this solution:

```
import { AppPages } from '../../support/constants';

function toggleCoockieHandling(win: Cypress.AUTWindow, enabled: boolean): void {
  Object.defineProperty(win.navigator, 'cookieEnabled', {
    value: enabled,
    writable: !enabled,
  });
  Object.defineProperty(win.document, 'cookie', {
    value: '',
    writable: !enabled,
  });
}

describe('Should [Login]', () => {
  before(function () {
    cy.task('db:reload');
    Cypress.on('window:before:load', win => toggleCoockieHandling(win, false));
  });

  after(function () {
    Cypress.on('window:before:load', win => toggleCoockieHandling(win, true));
  });

  it.only('should show cookies page if disabled', function () {
    cy.visit(AppPages.Login);
    cy.get('.content h1').should('be.visible').contains('Cookies are required.');
  });
});
```

**Comment by arberosmani** [comment]
@JohnnyDevNull 

This works. But I had to add the property `configurable: true` otherwise I got an exception:

```
Uncaught TypeError: Cannot redefine property: cookieEnabled
    at Function.defineProperty (<anonymous>)
```

I also had to remove the second `defineProperty`  for the `cookie` property. Otherwise I got the following exception:

```
ERROR TypeError: Cannot assign to read only property 'cookie' of object '[object HTMLDocument]'
    at CookieService.set (ngx-cookie-service.mjs:149:9)
    at CookieService.set (ngx-cookie-service.mjs:117:18)
```

But this is for my test case not relevant. So finally the solution for me looks like this:

```js
function toggleCoockieHandling(win: Cypress.AUTWindow, enabled: boolean) {
  Object.defineProperty(win.navigator, 'cookieEnabled', {
    value: enabled,
    writable: false,
    configurable: true
  });
}

describe('foo', () => {
  before(function () {
    Cypress.on('window:before:load', win => toggleCoockieHandling(win, false));
  });

  after(function () {
    Cypress.on('window:before:load', win => toggleCoockieHandling(win, true));
  });

  it('bar', () => {
     // ...
  })
});
```

Thanks alot.
