### ISSUE TITLE
specWindow.Error is not a constructor

### ISSUE THREAD

**Issue by jprealini** [cypress-io/cypress-example-recipes#552]
Since I upgraded to 5.0 I am seeing this from time to time in the test logs

```
specWindow.Error is not a constructor

at $Cy.cy.<computed> [as log] (http://localhost:4001/__cypress/runner/cypress_runner.js:168813:78)
at Context.runnable.fn (http://localhost:4001/__cypress/runner/cypress_runner.js:169078:22)
at callFn (http://localhost:4001/__cypress/runner/cypress_runner.js:103957:22)
at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:4001/__cypress/runner/cypress_runner.js:103944:8)
at <unknown> (http://localhost:4001/__cypress/runner/cypress_runner.js:174727:29)
at PassThroughHandlerContext.finallyHandler (http://localhost:4001/__cypress/runner/cypress_runner.js:6406:24)
at PassThroughHandlerContext.tryCatcher (http://localhost:4001/__cypress/runner/cypress_runner.js:9852:24)
at Promise._settlePromiseFromHandler (http://localhost:4001/__cypress/runner/cypress_runner.js:7787:32)
at Promise._settlePromise (http://localhost:4001/__cypress/runner/cypress_runner.js:7844:19)
at Promise._settlePromise0 (http://localhost:4001/__cypress/runner/cypress_runner.js:7889:11)
at Promise._settlePromises (http://localhost:4001/__cypress/runner/cypress_runner.js:7969:19)
at <unknown> (http://localhost:4001/__cypress/runner/cypress_runner.js:4544:26)
```
Then the test retries, and passes... 
Is this any known issue?

Running cypress on windows.

**Comment by bahmutov** [comment]
I am not sure if this is related to this repo or something else.
